---
- name: Include OS specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Create and setup restic
  include_tasks: create.yml
  when: restic_state == "present"

- name: Destroy all restic resources
  include_tasks: teardown.yml
  when: restic_state == "absent"
