---
# present/absent - add or remove grafana
grafana_state: present
# if removing grafana, keep data volumes or not?
grafana_keep_volumes: true

# docker images and tags
grafana_app_image_tag: "5.2.3"

# docker networks to join
grafana_default_network: grafana
# overwrite to connect to other networks e.g. for other services
# e.g.
# grafana_additional_networks: 
#   - name: prometheus_frontend
grafana_additional_networks: []

# exposed port
grafana_port: 3000

# environment variable config
# all config can be set here as documented http://docs.grafana.org/installation/docker/
# to install plugins set the `GF_INSTALL_PLUGINS` variable
# e.g.
# grafana_environment_varibales:
#   GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
grafana_environment_variables: {}

# working directory
grafana_working_directory: /opt/grafana-docker

# traefik proxy configuration
# ignore if not using traefik. 
# enabling traefik will remove any published ports so communication must go through
# traefik connected to the {{ grafana_default_network }}
grafana_traefik_enable: false
# Define a frontend rule for direction as per the traefik documentation
# https://docs.traefik.io/configuration/backends/docker/
# https://docs.traefik.io/basics/#frontends
# Join multiple rules with `;`
grafana_traefik_frontend_rule: "Host: grafana.example.com"
grafana_traefik_allowed_hosts:
  - grafana.examle.com
# override this block for complete control of the traefik labels
grafana_traefik_labels: 
  traefik.docker.network: "{{ grafana_default_network }}"
  traefik.enable: "true"
  traefik.port: "3000"
  traefik.backend: grafana
  traefik.backend.healthcheck.path: /api/health
  traefik.frontend.headers.allowedHosts: "{{ grafana_traefik_allowed_hosts | join(',') }}"
  traefik.frontend.rule: "{{ grafana_traefik_frontend_rule }}"

#########################################################
# Note: Do not overwrite anything below this line
# All variables below are only used for convenience
#########################################################
grafana_published_ports:
  - "{{ grafana_port }}:3000"

# docker volumes
grafana_volumes:
  - app_data

# docker images
grafana_images:
  - image: "grafana/grafana"
    tag: "{{ grafana_app_image_tag }}"
