---
# present/absent - add or remove grafana
grafana_state: present
# if removing grafana, keep data volumes or not?
grafana_keep_volumes: true

# docker images and tags
grafana_app_image_tag: "5.2.3"

# docker networks to join
grafana_default_network: grafana
# overwrite to connect to other networks e.g. for other services
# e.g.
# grafana_docker_networks: 
#   - name: prometheus_frontend
grafana_additional_networks: []

# exposed ports
grafana_port: 3000

# environment variable config
# all config can be set here as documented http://docs.grafana.org/installation/docker/
# to install plugins set the `GF_INSTALL_PLUGINS` variable
# e.g.
# grafana_environment_varibales:
#   GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
grafana_environment_variables: {}

# working directory
grafana_working_directory: /opt/grafana-docker

# traefik proxy configuration
# ignore if not using traefik, some labels may get added to 
# containers but nothing else should be done
traefik_grafana_enable: "true"
traefik_grafana_allowed_hosts:
  - grafana.examle.com

#########################################################
# Note: Do not overwrite anything below this line
# All variables below are only used for convenience
#########################################################

# docker volumes
grafana_volumes:
  - app_data

# docker images
grafana_images:
  - image: "grafana/grafana"
    tag: "{{ grafana_app_image_tag }}"
